apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:5.7
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 3306 # mysql default port
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: somewordpress
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              value: wordpress
      #
      # Uncomment the following lines to enable persistent volume for the db pod
      #
      #     volumeMounts:
      #       - name: mysql-pv
      #         mountPath: /var/lib/mysql
      # volumes:
      #   - name: mysql-pv
      #     persistentVolumeClaim:
      #       claimName: mysql-pvc